export const transactionTableData = [
    {
      niumId: "N-001",
      bmfId: "BMF-001",
      orderDate: "18.02.2025",
      customerPan: "AFJPW0198D",
      transactionType: "Card Load",
      fxCurrency: "USD",
      fxValue: "10,000.00",
      fxRate: "85.20",
      inrRate: "8,52,000.00",
      purposeType: "BTQ",
      esignStatus: "Success",
      vkycStatus: "Success",
      incidentStatus: "Approved",
    },
    {
      niumId: "N-002",
      bmfId: "BMF-002",
      orderDate: "10.02.2025",
      customerPan: "AHURE123R",
      transactionType: "Card Reload",
      fxCurrency: "EUR",
      fxValue: "4,000.00",
      fxRate: "109.10",
      inrRate: "4,36,400.00",
      purposeType: "BT",
      esignStatus: "Pending",
      vkycStatus: "Pending",
      incidentStatus: "Pending",
    },
    {
      niumId: "N-003",
      bmfId: "BMF-003",
      orderDate: "05.01.2025",
      customerPan: "AJYOI8986E",
      transactionType: "Encashment",
      fxCurrency: "CAD",
      fxValue: "2,000.00",
      fxRate: "78.20",
      inrRate: "1,56,400.00",
      purposeType: "-",
      esignStatus: "Expired",
      vkycStatus: "Expired",
      incidentStatus: "Expired",
    },
    {
      niumId: "N-004",
      bmfId: "BMF-004",
      orderDate: "28.12.2024",
      customerPan: "BYUOW345T",
      transactionType: "Remittance",
      fxCurrency: "USD",
      fxValue: "40,000.00",
      fxRate: "85.40",
      inrRate: "34,16,000.00",
      purposeType: "University Fee - Self Funded",
      esignStatus: "Rejected",
      vkycStatus: "Success",
      incidentStatus: "Pending",
    },
  ];
  